### ISSUE TITLE
Code license

### ISSUE THREAD

**Issue by alfred-ai** [grygorek/FreeRTOS_cpp11#19]
Hi Piotr,

I see some very nice work here :+1: :+1: :clinking_glasses: 

FYI you have answered the wish from another [FreeRTOS+CPP project](https://github.com/richard-damon/FreeRTOScpp/issues/8).

I read through some of your code and I believe the licensing terms is close to MIT. Would you mind add a license file to the root folder for clarification?

Thanks,
Alfred

**Comment by grygorek** [comment]
Hi Alfred,

First of all, thanks for the interest and feedback!

Yes, you are right that the license requires clarification. I have been procrastinating the license topic for a while. I agree that my license is close to MIT and probably would be good if I switch to it. There is one issue with it which holds me back.

I copied two files from GCC compiler - mutex.cc and future.cc. They are released under [GPLv3](https://www.gnu.org/licenses/gpl-3.0.html) with [GCC exception](https://www.gnu.org/licenses/gcc-exception-3.1.en.html). So, now...

1. Does it mean I should release my library with GPLv3? Probably yes.
2. Does the exception change anything? The definition of the "Independent Module" makes me thinking that it does not change anything in this case (... based on Runtime Library).
3. Or maybe I should still release it as MIT but with a note that MIT is applied only if a user of my library removes the two GCC files from his/her product. Otherwise GPLv3 it is.
4. Create my own implementation of functions in mutex.cc and future.cc. There will be no dependency on GPLv3.

The easiest option is to release it as GPLv3 but that will close the door for usage of this library for proprietary non-open source products.

Option 4 is interesting but the original code is so simple it would be hard to avoid the exact same implementation.

Option 3 is interesting but not sure if legally possible. Secondly, it would exclude from the project the futures library.

If you have experience with licensing I would be happy to hear your opinion (or anybody who is reading this).
